on:
  push:
    branches: main

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@main
      - uses: DeterminateSystems/magic-nix-cache-action@main
      - uses: DeterminateSystems/flake-checker-action@main

      - run: nix run .#publish
        env:
          # https://www.npmjs.com/settings/aabccd021/tokens/granular-access-tokens/new
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
